# Shares helper functions with pages and routes.
"""Re-exports for backwards compatibility. Import from the focused sub-modules directly."""
from app.analytics import (  # noqa: F401
    build_activity_heatmap,
    build_filtered_top_markets,
    build_filtered_top_wallets,
    build_top_markets,
    build_wallet_activity_timeline,
    compute_performance_from_trades,
    compute_wallet_performance,
    compute_wallet_performance_map,
    detect_interesting_activity,
    get_wallet_intelligence_summary,
)
from app.formatting import (  # noqa: F401
    WALLET_STALE_HOURS,
    active_wallets,
    date_preset_range,
    duration_label,
    format_compact_currency,
    format_compact_number,
    format_full_currency,
    format_percent,
    pagination_meta,
    parse_datetime_end,
    parse_datetime_start,
    short_address,
    side_bias,
    signal_label,
    signal_tone,
    sync_status_class,
    wallet_freshness_label,
    wallet_status_tone,
)
from app.queries import (  # noqa: F401
    WALLET_ADDRESS_RE,
    apply_trade_filters,
    apply_wallet_search_to_trade_query,
    build_wallet_query,
    filter_sync_events,
    normalize_tags,
    sorted_trade_query,
    tag_list,
    trade_pnl_summary,
    validate_wallet_address,
    wallet_order_query,
    wallet_stats_map,
    wallet_summary_counts,
)
